### ISSUE TITLE
[Feature]/[Question] - list out sub tags in hatchery on tag page

### ISSUE THREAD

**Issue by lordmatt** [pjeby/tag-wrangler#108]
Is there a way (or can one be made) to list out the subtags for a tag page? For example, would this work or be made to work with Dataview?

So if you had #foo/bar #foo/baz and #foo/boo you can automatically add to the tag page for #foo:

 - #foo/bar
 - #foo/baz
 - #foo/boo

**Comment by pjeby** [comment]
Dataview can do a "group by" operation, but you might need Javascript for this specific thing.  I'd suggest asking on the dataview channel of the Discord to see if someone there knows how.  Rather than asking about tag pages at first, though, I'd suggest just asking how to make the list for a specific tag.  You could possibly do that without any Javascript, but to make a generic dataview that looks at the aliases field in the note will almost certainly require Javascript.
