### ISSUE TITLE
[Question] I don't understand how to use TagPage, is there any example use cases?

### ISSUE THREAD

**Issue by maxoja** [pjeby/tag-wrangler#126]
I gave a read on https://github.com/pjeby/tag-wrangler?tab=readme-ov-file#tag-pages and it explains that it should help giving you the benefits of both linking and tagging worlds and focused on how to manage tag pages.

However, I'm new to tagging and want to understand the use cases of tag pages and what additional things we can do or have from using it compared against only using tags. My guess is that this is so we can have a tag node on a graph view and so notes can be more organized on that view but may be that's not all. Can you tell me more on this area? - thanks!

**Comment by pjeby** [comment]
Tag pages just let you have a page that you can access by clicking on the tag, either in the tag pane or elsewhere.  It means you can use tag autocompletion instead of link autocompletion to link to that page.  Some people use them for information about the tag, or to have dataviews listing notes with the tag.  You can also use tag pages as a way to transition a tag to a page, if you started with tags and would rather have pages.

**Comment by maxoja** [comment]
Aha that's very useful and gave me some ideas. Thanks a lot for the answer and this project. I will close this now
