### ISSUE TITLE
[bug] renaming a tag mess up yaml formating

### ISSUE THREAD

**Issue by www-wagner** [pjeby/tag-wrangler#136]
I have a _index file_ that I use as reference for the tags I _should use_ in the vault. As I use sub tags, I usually indent them in YAML section, only for readability purpose (I can collapse and expand sub items, for example).

In the example below:
```yaml
---
tags:
  - tag1
    - tag1/tag1_1
    - tag1/tag1_2
  - tag2
    - tag2/tag2_1
      - tag2/tag2_1/tag2_1_1
    - tag2/tag2_2
---
```

When I try to rename the `tag2`:
![Screenshot_20240619_170945](https://github.com/pjeby/tag-wrangler/assets/18124316/ba05547c-ff8e-4ff3-9c62-fa4b35da5224)

The result is:
```yaml
---
tags:
  - tag1
    - tag1/tag1_1
    - tag1/tag1_2
  - tag3 - tag3/tag2_1 - tag3/tag2_1/tag2_1_1 - tag3/tag2_2
---
```

Despite the syntax is still valid, the format becomes ugly.

Would it be possible to rename the tag without losing the original format?

**Comment by pjeby** [comment]
Yes: add a `|` like so:

```
---
tags: |
  - tag1
    - tag1/tag1_1
    - tag1/tag1_2
  - tag2
    - tag2/tag2_1
      - tag2/tag2_1/tag2_1_1
    - tag2/tag2_2
---
```

This will make it so that, instead of having a list of strings at the top level, it's all one string.  The problem right now is that you have what *looks* like nested lists to a human reader, but to YAML it is a list of only *two* strings (items `- tag1` and  `- tag2`) with extra whitespace and dashes around the tags.  Making the entire field one whitespace-sensitive string (via the `|`) means TW will just replace the tags in that string without altering the formatting.

(Do note that if you ever edit the metadata for a note via Obsidian's properties pane or any plugins, you will lose the formatting altogether, as the property-editing APIs provided by Obsidian destroy all formatting when they update a note.)

**Comment by www-wagner** [comment]
For my purpose, it's all right! That file is for reference only and I always edit it in source mode or using Tag Wrangler to rename tags.

By the way, I can even remove the dashes like below and the tags are recognized properly.

```yaml
---
tags: |
  tag1
    tag1/tag1_1
    tag1/tag1_2
  tag2
    tag2/tag2_1
      tag2/tag2_1/tag2_1_1
    tag2/tag2_2
---
```

Thank you so much! I'll close the issue.

**Comment by www-wagner** [comment]
For my purpose, it's all right! That file is for reference only and I always edit it in source mode or using Tag Wrangler to rename tags.

By the way, I can even remove the dashes like below and the tags are recognized properly.

```yaml
---
tags: |
  tag1
    tag1/tag1_1
    tag1/tag1_2
  tag2
    tag2/tag2_1
      tag2/tag2_1/tag2_1_1
    tag2/tag2_2
---
```

Thank you so much! I'll close the issue.

**Comment by pjeby** [comment]
Yep, and then you don't get a `#-` tag showing up in your tags view either.  😁
