### ISSUE TITLE
Export tags in text/Markdown

### ISSUE THREAD

**Issue by patel934** [pjeby/tag-wrangler#144]
I have 1000+ codes in my tag tree using Tag Wrangler and would like to export them easily in a hierarchy. Is that possible?

**Comment by pjeby** [comment]
Googling "obsidian tag list export" found this thread with a few different ways to do it: https://forum.obsidian.md/t/hi-everyone-i-want-to-paste-all-my-tags-in-a-note-just-my-tags-as-a-list-dont-want-to-use-the-dataview-plugin-though-any-thoughts-cheers/42016

Hope that helps!

**Comment by pjeby** [comment]
This kind of functionality is really better suited to tools like Dataview or Templater, because they let you customize how the output will work.  If I tried to add this feature I would be inundated with people wanting tabs instead of spaces, or csv or json or OPML, or yes, markdown, but I want numbered lists or checkboxes...  Just not gonna happen.

Tag Wrangler does provide an event hook to let other plugins add to its menu.  So if someone makes a tag export plugin they can easily add that functionality to the TW menu... and then they can be the ones to handle all the many ways that people might want to export. :grin:

**Comment by patel934** [comment]
Good to know, still learning the ins and outs of Obsidian and its many plugins.

**Comment by pjeby** [comment]
Good luck on finding a solution that works for you!
