### ISSUE TITLE
Use Obsidian's Modal class

### ISSUE THREAD

**Issue by liamcain** [pjeby/tag-wrangler#3]
I've finally started using tags in my workflow and the plugin works great! 😄

It would be awesome if the rename tag modal used Obsidian's `Modal` class + class names though so that it would match the current theme. Currently the modal is illegible in many of the Community themes.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/693981/107854559-a13f7f00-6dea-11eb-90b6-544de4c66803.png">

**Comment by pjeby** [comment]
Pull requests welcome.  ;-)

More seriously, though, that looks more like a "CSS needs some extra props" problem than a "replace the modal class" problem.  I chose the library I did because it has proper keyboard+focus support, not to mention a progress bar.

So if you can point me to the illegible themes/modes, I'll investigate what's missing from the library's CSS to handle those, and add them to the plugin's CSS.  (In the picture you've given, it looks like the issue is that the input field has been styled with a background color by the theme, but the text color is being set by the modal library.

(Which is to say that the input field probably needs an explicit background setting to override the theme, here, or perhaps a full reset to match the user-agent stylesheet.)

**Comment by pjeby** [comment]
I'm still waiting on the name of the theme(s) that have the problem, by the way.  I could try to guess about setting the background, but I'd have no way to know if I'd fixed it or not without being able to try the theme in question.

**Comment by pjeby** [comment]
0.4.2 now uses theme color variables, so this should no longer be an issue.  The key piece of info missing from this bug report was that dark mode was in use -- without that info or at least a theme to try, there was no way for me to reproduce the issue.
