### ISSUE TITLE
[Feature request] Default directory for Tag Pages

### ISSUE THREAD

**Issue by colintedford** [pjeby/tag-wrangler#37]
I'd like to be able to specify in which folder Tag Pages are created.

(Sorry to request a feature that would require a settings page.)

**Comment by pjeby** [comment]
Tag Wrangler uses the Obsidian default directory setting, so if for example it's set to "current directory", then they'll go in whatever directory your active note is in.

I'd suggest using a plugin like Templater or QuickAdd to do this instead, since there isn't anything special about how TW creates the tag pages: they're just a note with an alias in the front matter, so you can use any templating tool to make a file anywhere you like.  Both Templater and QuickAdd can prompt for input and create a file according to a template in a specified location, and will give you a lot more flexibility.

**Comment by colintedford** [comment]
I don't want to choose a folder each time I make a tag page, just to set which one they're all created in — "Default location for new attachments", except for tag pages.

**Comment by pjeby** [comment]
And that's why you should use a plugin like Templater or QuickAdd, because they can do things like that, without needing to ask you for a folder.  QuickAdd, for example, would let you create a custom command that expands a template to a new file in a specified folder, and then opens the file,  You could even include your search embed in the template.  The command can prompt you for the tag name in the process, or take it from a selection or the clipboard.  And so on.

To be clear, I do not expect to ever implement the feature you're requesting; I'm making these suggestions so you know what other options you have available.  In my case, if I needed to make a bunch of tag pages in a row in the same folder, I'd just open something from that folder (like an existing tag page) and then make the tag pages.  (I have Obsidian set to create new notes in the current folder.)

So your options are:

1. Configure Obsidian to create notes in the current folder by default, then open an existing tag page before creating a new one.  (Or set a hotkey for the "Move file to another folder" command -- I use shift-F2 personally.)
2. Use a plugin like QuickAdd, Templater, etc. to define a custom command to create a page in the desired folder using a template containing whatever you'd like your tag pages to contain.

The advantage of option 2 is that of course you can customize the template as well.  (Although I understand that Templater can perform actions when new files are created, so it's possible you could get option 1 to also do templates with an appropriate plugin selection.)

**Comment by colintedford** [comment]
Thanks, I appreciate your taking the time to write all of that. I'd looked at QuickAdd before, but not very closely because its README lacks a good intro to the plugin. I have a better sense of it now. Templater seems a little more complex and powerful than I want in a plugin, but that's not your problem. :)
