### ISSUE TITLE
FR : is it possible to treat *aliases tags* like *real tags* ?

### ISSUE THREAD

**Issue by safrilth** [pjeby/tag-wrangler#40]
i'm just curious for the future development..

is it possible to treat *aliases tags* like *real tags* ?

![Pasted image 20220217162326](https://user-images.githubusercontent.com/54169984/154449295-5f5d4770-b178-4484-8303-82f4ebc5a433.jpg)

- ❓ for problem above ?
	- ✅ workaraound -> instead `FROM #tag` we can use `FROM [[#tag-link-aliases]]`

- ❓ how about other plugin that leverage uses of tag ?
	- there are so many plugin that uses tag as their input

- 💡 if it's possible -> this feature allows interopability with other plugin -> game changer

**Comment by pjeby** [comment]
I don't understand the question.  It seems you're implying there is a problem in the picture, but I don't see one.  Tag pages should not show up in Dataview or other tag searches, for the same reason a regular note is not listed in its own backlinks list unless it actually links to itself!  In the same way, a tag page does not show in a listing of pages with that tag, unless you actually put the tag in it.

Consider a tag like `#to-review`.  If you have a tag page for it, that does not mean that the *tag page* needs reviewing.  So if tag pages were listed as having the tag, there would always be at least one note on the `#to-review` list even though there is nothing to review!

In other words, making tag pages show as part of the tag's note set by default would be a **huge** problem for people who are using tag pages to manage processing lists like this, because they would have no easy way to exclude the tag page from searches, and the tag count would always show as having one more note than really needs reviewing.  And there would be no workaround possible.

In contrast, if you want to use tags for something other than such processing lists, and for some reason want it to be included as a tagged page, you can always enter it explicitly in the page or front matter.  And if you always want it that way, you can use a plugin like QuickAdd or Templater to generate new tag pages with the duplicated tag.  Tag Wrangler will handle renames for you as well (of both the alias and second tag), so you won't really need to do anything else.

**Comment by safrilth** [comment]
Okay, thank you for response.. 
Seems to be clear solution for me..
