### ISSUE TITLE
Purpose of Alias Page?

### ISSUE THREAD

**Issue by PKeyes505** [pjeby/tag-wrangler#50]
What is the Purpose of the Alias Page?

What I was hoping for is that if I searched for "tag:dog", I would get everything with the tag:cannie, tag:pooch

Title:dog
---
Aliases: [ "#cannie, #pooch ]
---

**Comment by pjeby** [comment]
What you have above means "this page is the tag page for both of these tags".  What you are apparently looking for is a way to make tags synonyms, which as far as I know does not exist.  If you want these tags to be the same as dog, you can simply rename them to "dog" and all existing instances will then say `#dog` instead.  You could also rename them to `#dog/pooch` and `#dog/canine`, in which case searches for `#dog` would find them.

So, there is no way to have synonyms, but you can use the rename to group tags in a hierarchy, or just consolidate them to a single tag.

**Comment by PKeyes505** [comment]
So the Tag Page is used to keep track of the Tag's rename history?  Is it also used for documenting the definition of the Tag?  What do you use it for.  Sry for the 20 questions.

**Comment by pjeby** [comment]
No, the tag page does not track rename history.  Tag pages *can* be used for documenting the definition of the tag, or as a stepping-stone to replacing the tag with a note.  It allows you to tag things as you wish and then later decide you'd like to have a note.  Some people add dataviews or other embeddable searches to display notes or tasks with the tag.  If you have Hover Editor or Page Preview turned on, then you can ctrl- or cmd- hover the tag to display the tag page in a popup, so anything you might want (such as a definition, notes about the tag, other references to it, etc.) is a useful application of tag pages.

Essentially, tag pages are just for you to have content that is about the tag, rather than content the tag is about.  That is, if a note containing `#dog` is presumably saying the subject of the note is a dog, but the tag page for `#dog` is a note about *the tag* `#dog`, rather than being about a dog.

If you don't need notes that are *about* the tags themselves (e.g. for definitions, procedures, searches, quick reference, etc.) then you probably do not need to use tag pages.

**Comment by PKeyes505** [comment]
I do believe that everyone should have notes about tags.  Thank you for the responses and the plugin.
