### ISSUE TITLE
Add automatic Dataview query edits when changing tags

### ISSUE THREAD

**Issue by Yyote** [pjeby/tag-wrangler#52]
What we currently have:
1. Change tag name
2. Dataview queries are not changed
3. Dataview queries lose their results

What is expected:
1. Change tag name
2. Dataview queries that have this tag are changed accordingly
3. Dataview queries don't change their results

**Comment by pjeby** [comment]
If the Dataview authors are willing to provide the code to parse a dataview query and do the replacement, I can add support to Tag Wrangler to call their plugin.  But this isn't a feature I can provide directly.  Dataview isn't the only code block syntax that can reference tags, and dataviewjs blocks would be even more challenging to support.  Some plugins reference tags in their settings as well.  So, in order to allow these other plugins to do replacements, I can have tag wrangler issue events or provide some type of API to allow it to be done, but the actual "understanding" of code blocks and the changing of plugin settings has to be done by the other plugins involved.
