### ISSUE TITLE
can we support tag-folder plugin?

### ISSUE THREAD

**Issue by liangzh-404** [pjeby/tag-wrangler#54]
Right now I am using tag-folder more often. What I missed is the ability to bulk update/add/delete tags, so I have to keep the original tag pane as well and when I need to update, I need to go back to the original one.
That will be great if I can do that directly in tag-folder

**Comment by pjeby** [comment]
The built-in tag pane supplies data on what tag each item is, which tagfolder does not.  Tagfolder also can have items that represent *multiple* tags, which Tag Wrangler would also not be able to handle correctly.  Finally, Tagfolder itself has a context menu, so if Tag Wrangler were to take it over, you would lose the TagFolder functionality from its menu.

Basically, in order to integrate this, TagFolder would have to trigger an event during the creation of its menu to tell Tag Wrangler about it.  Then Tag Wrangler would be able to add items to its menu.  The event would need to include the applicable tag(s) as well as the menu object itself.  If they can add that on their side then I can add some items to their menu (for single-tag items).
