### ISSUE TITLE
Appending new tags to certain tagged pages

### ISSUE THREAD

**Issue by liveod3** [pjeby/tag-wrangler#8]
Thank you for your dedication towards this plugin! It works perfect with the current work flow.

It would be awesome if we could append new tags after the tag of certain tagged pages or searching results.

**Comment by pjeby** [comment]
On review of this request, I have to admit I don't understand what it's actually asking for.  (The original request and the subsequent comment also seem to perhaps be describing different things.)

If either of those things are still desired, I would suggest opening separate requests for each one, with much more detail/examples so that I can understand exactly what is being asked for.  Thanks.
