### ISSUE TITLE
Filter tags list in tag pane when selecting multiple tags

### ISSUE THREAD

**Issue by gala8y** [pjeby/tag-wrangler#9]
I wonder if this would be possible for you to create such a functionality, that...

tags list gets filtered when choosing (clicking on) tags, so only tags that occur in documents together with selected tag(s) are shown in the list. Every click (another selected tag) narrows list down, deselecting previously selected tag widens list back.

(text copied from a feature request on forum: https://forum.obsidian.md/t/filter-tags-list-in-tag-pane-when-choosing-tags/12352)

**Comment by pjeby** [comment]
Possible?  Yes.  Going to?  No.  It would be a major undertaking, and not one that would directly serve my needs at the present moment.  If you want to analyze tags in this manner, I would suggest as a workaround that you try the dataview plugin, with one pane being in preview mode.  You can then run queries grouping by document tags and such.  That is, at least, what I would try first if I were attempting to analyze tags like this.  Or perhaps the OQL plugin.  (To be honest I'm not 100% sure which of those would be suitable, but I do know they are far more complex plugins than this one, in order to do the necessary querying.)

Sorry I couldn't be of more help.

**Comment by gala8y** [comment]
Thank you very much for your answer. Honestly, I dont know scope of the work required, that's the reason I wrote.  I think this belongs to core functionality anyway (simple and powerful 'must have' if anyone really thinks about using tags efficiently). Thanks again for answer and workarounds.  All the best! :)
